task:
  name: "Capher"
  timeout_in: 100000m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
      
  Sync_script:
      - cd ~
      - mkdir rom
      - cd rom
      - repo init -u https://github.com/ForkLineageOS/android.git -b lineage-19.0 -g default,-mips,-darwin,-notdefault
    
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags


  Build_script: 
      - export ALLOW_MISSING_DEPENDENCIES=true
      - cd ~
      - cd rom
      - export BUILD_BROKEN_DUP_RULES=true
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 60G
      - source build/envsetup.sh
      - lunch lineage_juice-userdebug
      - make lineage -j8

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~
      - cd rom
      - cd out/target/product/selene
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file V*.zip https://transfer.sh
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"

