task:
  name: "absssi"
  timeout_in: 100000m  
  container:
      image: debian:latest
      cpu: 16
      memory: 32G
      
  Sync_script:
      - cd ~
      - mkdir rom
      - cd rom
      - repo init -u  git://github.com/PixelExperience/manifest -b twelve -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/Dullest-Pants/local_manifest.git --depth 1 -b main .repo/local_manifests
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags


  Build_script: 
      - export ALLOW_MISSING_DEPENDENCIES=true
      - cd ~
      - cd rom
      - export BUILD_BROKEN_DUP_RULES=true
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 60G
      - source build/envsetup.sh
      - lunch aosp_juice-userdebug
      - mka bacon -j8

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~
      - cd rom
      - cd out/target/product/selene
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file V*.zip https://transfer.sh
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"

