task:
  name: "RsOMM"
  timeout_in: 10000m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
      
  Sync_script:
      - cd ~
      - mkdir rom
      - cd rom
      - repo init --depth=1 --no-repo-verify -u https://github.com/ForkLineageOS/android.git -b lineage-19.0 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/Jaxer159/manifests --depth 1 -b pe+_11_temporary_juice .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

  Build_script: 
      - export ALLOW_MISSING_DEPENDENCIES=true
      - cd ~
      - cd rom
      - export BUILD_BROKEN_DUP_RULES=true
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 60G
      - source build/envsetup.sh
      - lunch aosp_juice-userdebug
      - mka bacon -j8

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~
      - cd rom
      - cd out/target/product/selene
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file V*.zip https://transfer.sh
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"

