version: 2.0



jobs:
  build:
  
    docker:
      - image: ghcr.io/iamshubh69/docker:main
       
    resource_class: large
  
    steps:
      - checkout
      - run: sudo apt-get -y update
      - run: sudo apt -y install python build-essential python3 
      - run: cd ~
      - run: ENV mkdir rom
      - run: cd rom
      - run: repo init --depth=1 --no-repo-verify -u https://github.com/xdroid-oss/xd_manifest -b twelve -g default,-mips,-darwin,-notdefault
      - run: git clone https://github.com/iamshubh69/local_manifest --depth 1 -b main .repo/local_manifests
      - run: repo sync --force-sync -j8
      - run: ls
      - run: |
          ENV . build/envsetup.sh && lunch aosp_moon-userdebug
      - run: ls
      - run: export USE_CCACHE=1
      - run: export CCACHE_EXEC=/usr/bin/ccache
      - run: ccache -M 60G
      - run: source build/envsetup.sh && make xd
      - run: cd ~
      - run: cd rom
      - run: cd out/target/product/*
      - run: ls -lh
      - run: pwd
      - run: chmod 777 *
      - run: curl --upload-file V*.zip https://transfer.sh
      - run: echo " "
      - run: echo "============================"
      - run: echo "Build Uploaded!"
      - run: echo "Please see the link Below-  "
      - run: echo "----------------------------"
      - run: cat link.txt && echo " "
      - run: echo "============================"
  
