version: 2.1
  workflows:

      
      my_workflow:
        jobs:
          - build
          - buildo


jobs:
  build:
  
    docker:
      - image:  stupidkidaf/kernel_docker:v1
      
    resource_class: large
  
    steps:
      - checkout
      - run: sudo apt-get -y update
      - run: sudo apt -y install python build-essential python3 lunch
      - run: cd ~
      - run: mkdir rom
      - run: cd rom
      - run: repo init --depth=1 --no-repo-verify -u  https://github.com/PixelExperience/manifest -b twelve
      - run: git clone https://github.com/Dullest-Pants/local_manifest.git --depth 1 -b main .repo/local_manifests
      - run: repo sync
      - run: source build/envsetup.sh
      - run: ls
      - run: . build/envsetup.sh

      


  buildo:
    docker:
     - image:  stupidkidaf/kernel_docker:v1
      
    resource_class: large
  
    steps:
      - checkout
      - run: cd ~
      - run: cd rom
      - run: export BUILD_BROKEN_DUP_RULES=true
      - run: export USE_CCACHE=1
      - run: export CCACHE_EXEC=/usr/bin/ccache
      - run: ccache -M 60G
      - run: source ./build/envsetup.sh
      - run: lunch aosp_juice-userdebug
      - run: mka bacon -j$(nproc --all)
      - run: cd ~
      - run: cd rom
      - run: cd out/target/product/selene
      - run: ls -lh
      - run: pwd
      - run: chmod 777 *
      - run: curl --upload-file V*.zip https://transfer.sh
      - run: echo " "
      - run: echo "============================"
      - run: echo "Build Uploaded!"
      - run: echo "Please see the link Below-  "
      - run: echo "----------------------------"
      - run: cat link.txt && echo " "
      - run: echo "============================"
  
  
