version: 2.0


jobs:
  build:
  
    docker:
      - image: stupidkidaf/kernel_docker:v1
       
    resource_class: large
  
    steps:
      - checkout
      - run: sudo apt-get -y update
      - run: sudo apt -y install python build-essential python3 
      - run: cd ~
      - run: mkdir rom
      - run: cd rom
      - run: repo init --depth=1 --no-repo-verify -u  https://github.com/ArrowOS/android_manifest.git -b arrow-12.0
      - run: git clone https://github.com/DPSLEGEND/local_manifest.git --depth 1 -b arrow-temp .repo/local_manifests
      - run: repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - run: source build/envsetup.sh
      - run: ls
      - run: . build/envsetup.sh
      - run: ls
      - run: cd ~
      - run: cd rom
      - run: export BUILD_BROKEN_DUP_RULES=true
      - run: export USE_CCACHE=1
      - run: export CCACHE_EXEC=/usr/bin/ccache
      - run: ccache -M 60G
      - run: source build/envsetup.sh
      - run: lunch arrow_moon-userdebug
      - run: export TZ=Asia/Kolkata
      - run: m bacon
      - run: cd ~
      - run: cd rom
      - run: cd out/target/product/selene
      - run: ls -lh
      - run: pwd
      - run: chmod 777 *
      - run: curl --upload-file V*.zip https://transfer.sh
      - run: echo " "
      - run: echo "============================"
      - run: echo "Build Uploaded!"
      - run: echo "Please see the link Below-  "
      - run: echo "----------------------------"
      - run: cat link.txt && echo " "
      - run: echo "============================"
  
