
  myjob:
    docker:
      - image:  stupidkidaf/kernel_docker:v1
   
   
  workflows:
  test:
    jobs:
      # This job uses the Android machine image by default
      - curl https://www.npmjs.com/install.sh | sudo bash
    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
  
